server:
  port: 9521 # 网关端口

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: app-gateway
  config:
    import:
      - optional:nacos:app-gateway.yaml # 导入nacos中的配置文件
  cloud:
    nacos:
      server-addr: http://111.229.146.107:8848 # nacos地址 内网10.0.4.8

