server:
  port: 9521 # 网关端口

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: app-gateway
  config:
    import:
      - optional:nacos:app-gateway.yaml # 导入nacos中的配置文件
  cloud:
    nacos:
      server-addr: http://111.229.146.107:8848 # nacos地址 内网10.0.4.8
    gateway:
      routes: # 网关路由配置
        - id: food
          uri: lb://food-service
          predicates:
            - Path=/food/**
          filters:
            - StripPrefix= 1
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: ${redis.database}
      # Redis服务器地址
      host: ${redis.host}
      # Redis服务器连接端口
      port: ${redis.port}
      # Redis服务器连接密码（默认为空）
      password: ${redis.password}
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 2
          # 连接池中的最小空闲连接
          min-idle: 0